Repository k8tz/k8tz, pull requests merged in 2022-07, with the labels that each got.

#27 Remove volummount implanted by other operators to avoid conflicts
  pkg/inject/inject.go
  pkg/inject/inject_test.go
  pkg/inject/testdata/test-pod-volumeMounts-initContainer-result.yaml
  pkg/inject/testdata/test-pod-volumeMounts-result.yaml
  pkg/inject/testdata/test-pod-volumeMounts.yaml
  pkg/inject/transform_test.go
Labels: bug, area/injection

#29 refactor(build): make tzdata image as k8tz base image
  Dockerfile
  Makefile
  tzdata/Dockerfile
  tzdata/Makefile
Labels: docker, area/build

#32 build(helm): release helm chart for k8tz v0.5.2
  charts/k8tz/Chart.yaml
Labels: area/helm
