Repository k8tz/k8tz, pull requests merged in 2022-12, with the labels that each got.

#45 feat: add support for managing certificate with cert-manager
  charts/k8tz/README.md
  charts/k8tz/templates/admission-webhook.yaml
  charts/k8tz/templates/certificate.yaml
  charts/k8tz/values.yaml
Labels: enhancement, area/helm

#50 build(helm): release helm chart 0.11.0
  CHANGELOG.md
  charts/k8tz/Chart.yaml
Labels: area/helm

#52 docs: fix workflow badges url
  README.md
  charts/k8tz/README.md
Labels: area/documentation
