Repository k8tz/k8tz, pull requests merged in 2023-12, with the labels that each got.

#92 refactor(helm): allow using helm built-in namespace
  charts/k8tz/README.md
  charts/k8tz/templates/_helpers.tpl
  charts/k8tz/templates/admission-webhook.yaml
  charts/k8tz/templates/certificate.yaml
  charts/k8tz/templates/controller.yaml
  charts/k8tz/templates/namespace.yaml
  charts/k8tz/templates/rbac.yaml
  charts/k8tz/templates/service.yaml
  charts/k8tz/templates/serviceaccount.yaml
  charts/k8tz/templates/tests/test-connection.yaml
  charts/k8tz/values.yaml
Labels: enhancement, area/helm

#84 override injected initContainer name
  charts/k8tz/README.md
  charts/k8tz/templates/controller.yaml
  charts/k8tz/values.yaml
  cmd/inject.go
  cmd/webhook.go
  pkg/admission/admission.go
  pkg/admission/admission_test.go
  pkg/inject/inject.go
  pkg/inject/inject_test.go
  pkg/inject/testdata/initcontainerstrategy-custom-name.json
  pkg/inject/transform_test.go
Labels: enhancement, area/injection

#94 build: bump tzdata version to 2023d
  Dockerfile
  Makefile
  tzdata/Dockerfile
  tzdata/Makefile
Labels: area/tzdata
