Repository k8tz/k8tz, pull requests merged in 2023-03, with the labels that each got.

#61 chore: upgrade go to 1.18 and update dependencies to latest
  .github/workflows/go.yaml
  go.mod
  go.sum
  pkg/admission/testdata/review-unparsable-pod-response.json
Labels: area/build, area/security

#60 chore(github): upgrade github action versions
  .github/workflows/go.yaml
  .github/workflows/helm-lint.yaml
  .github/workflows/helm-release.yaml
Labels: ci

#62 ci(github): add goreleaser action
  .github/workflows/goreleaser.yaml
Labels: ci

#59 chore(helm): Add possibility to add custom labels to k8tz resources
  charts/k8tz/README.md
  charts/k8tz/templates/_helpers.tpl
  charts/k8tz/templates/controller.yaml
  charts/k8tz/values.yaml
Labels: enhancement, area/helm

#63 chore(goreleaser): resolve archives.replacements deprecation notice and add docker images to release notes
  .goreleaser.yaml
Labels: area/build

#55 feat: make http.Server get up2date tls key pair
  charts/k8tz/templates/controller.yaml
  charts/k8tz/templates/rbac.yaml
  charts/k8tz/values.yaml
  cmd/cert-watcher.go
  pkg/admission/server.go
  pkg/cert-watcher/watcher.go
  pkg/cert-watcher/watcher_test.go
Labels: enhancement, area/admission, area/cli, area/helm

#65 build: bump tzdata version to 2023b
  Dockerfile
  Makefile
  tzdata/Dockerfile
  tzdata/Makefile
Labels: area/tzdata
